[tool.poetry]
name = "metabolomics-analysis"
version = "0.1.0"
description = ""
authors = ["tonyabracadabra <tongxupeng.cpu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.6"
scipy = "^1.10.1"
matchms = "^0.23.1"
pandas = "^2.1.2"
apache-airflow = "^2.7.2"
dagster = "^1.5.6"
dagster-webserver = "^1.5.6"

[tool.poetry.group.dev.dependencies]
black = "^23.10.1"
mypy = "^1.6.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
